name: Android Build with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: circleci/android:api-30  # Or any Android-compatible Docker image

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java Environment
        env:
          JAVA_HOME: /usr/lib/jvm/java-1.8-openjdk  # Ensure Java path is set if needed
        run: echo "Java home set to $JAVA_HOME"

      - name: Build APK with Gradle
        run: ./gradlew assembleDebug  # Runs inside the container with pre-installed Gradle

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/*.apk
